/**
 * Drilling rules — the persisted, per-role form of `magicDriller`.
 *
 * Woodworking's driller is modal: you select faces, dial in a pattern, and it
 * writes holes into the model. Morti's panels are regenerated by the compiler
 * on every edit, so a one-shot write would be lost. Instead a rule is stored
 * against a `PanelRole` and re-applied on each compile — the same holes land on
 * every panel of that role, and they follow the panel as it resizes.
 *
 * Pure and framework-free so it can be unit-tested directly.
 */

import type { OperationType, PanelOperation, PanelRole } from './types'
import {
  type HolePatternSpec,
  type PanelBox,
  type PatternAnchor,
  type PatternKind,
  buildHoleOperations,
} from './operations'
import { ALL_PANEL_ROLES } from './panel-attributes'

/** Hole kinds a drilling rule can produce. Slots are edited per-panel. */
export type DrillOperationType = Extract<
  OperationType,
  'through-hole' | 'dowel-hole' | 'countersink' | 'counterbore'
>

export const DRILL_OPERATION_TYPES: { value: DrillOperationType, label: string, hint: string }[] = [
  { value: 'dowel-hole', label: 'Dowel hole', hint: 'Blind hole for a dowel, shelf pin, or cam bolt (magicDowels).' },
  { value: 'through-hole', label: 'Through hole', hint: 'Straight through the panel (drillHoles).' },
  { value: 'countersink', label: 'Countersink', hint: 'Conical seat for a flat-head screw (drillCountersinks).' },
  { value: 'counterbore', label: 'Counterbore', hint: 'Flat recess for a screw head or cam (drillCounterbores).' },
]

export interface DrillingRule {
  id: string
  enabled: boolean
  operationType: DrillOperationType
  /** Which face the holes are drilled from. */
  face: 'front' | 'back'
  /** Pilot diameter, metres. */
  diameter: number
  /** Blind depth, metres. Ignored by `through-hole`. */
  depth: number
  /** Head recess diameter for countersinks and counterbores, metres. */
  headDiameter: number
  /** Head recess depth for counterbores, metres. */
  headDepth: number
  /** Hardware code this drilling seats, for the BOM. */
  hardwareCode: string | null
  pattern: HolePatternSpec
}

export type DrillingMap = Record<PanelRole, DrillingRule[]>

/** The 32 mm system: the shelf-pin spacing every European cabinet jig uses. */
export const SYSTEM_32_SPACING = 0.032

export function defaultDrillingRule(id: string): DrillingRule {
  return {
    id,
    enabled: true,
    operationType: 'dowel-hole',
    face: 'front',
    diameter: 0.005,
    depth: 0.012,
    headDiameter: 0.010,
    headDepth: 0.006,
    hardwareCode: null,
    pattern: {
      kind: 'row',
      anchor: 'left',
      count: 4,
      rows: 1,
      spacing: SYSTEM_32_SPACING,
      rowSpacing: SYSTEM_32_SPACING,
      inset: 0.037,
      offset: 0,
    },
  }
}

export function defaultDrillingMap(): DrillingMap {
  const map = {} as DrillingMap
  for (const role of ALL_PANEL_ROLES) map[role] = []
  return map
}

// ---------------------------------------------------------------------------
// Sanitizing
// ---------------------------------------------------------------------------

const MAX_RULES_PER_ROLE = 8
const MAX_METRIC = 5

function metric(value: unknown, fallback: number): number {
  if (typeof value !== 'number' || !Number.isFinite(value) || value < 0) return fallback
  return Math.min(MAX_METRIC, Math.round(value * 1_000_000) / 1_000_000)
}

function count(value: unknown, fallback: number): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) return fallback
  return Math.max(1, Math.min(64, Math.round(value)))
}

function oneOf<T extends string>(value: unknown, allowed: readonly T[], fallback: T): T {
  return typeof value === 'string' && (allowed as readonly string[]).includes(value) ? value as T : fallback
}

const PATTERN_KIND_VALUES: PatternKind[] = ['single', 'row', 'grid', 'edge']
const PATTERN_ANCHOR_VALUES: PatternAnchor[] = ['top', 'bottom', 'left', 'right', 'center']
const DRILL_TYPE_VALUES = DRILL_OPERATION_TYPES.map(t => t.value)

export function sanitizeDrillingRule(input: unknown, id: string): DrillingRule {
  const source = (input ?? {}) as Partial<DrillingRule>
  const base = defaultDrillingRule(id)
  const rawPattern = (source.pattern ?? {}) as Partial<HolePatternSpec>
  return {
    id: typeof source.id === 'string' && source.id.length > 0 ? source.id : id,
    enabled: typeof source.enabled === 'boolean' ? source.enabled : base.enabled,
    operationType: oneOf(source.operationType, DRILL_TYPE_VALUES, base.operationType),
    face: oneOf(source.face, ['front', 'back'] as const, base.face),
    diameter: metric(source.diameter, base.diameter),
    depth: metric(source.depth, base.depth),
    headDiameter: metric(source.headDiameter, base.headDiameter),
    headDepth: metric(source.headDepth, base.headDepth),
    hardwareCode: typeof source.hardwareCode === 'string' && source.hardwareCode ? source.hardwareCode : null,
    pattern: {
      kind: oneOf(rawPattern.kind, PATTERN_KIND_VALUES, base.pattern.kind),
      anchor: oneOf(rawPattern.anchor, PATTERN_ANCHOR_VALUES, base.pattern.anchor),
      count: count(rawPattern.count, base.pattern.count),
      rows: count(rawPattern.rows, base.pattern.rows ?? 1),
      spacing: metric(rawPattern.spacing, base.pattern.spacing),
      rowSpacing: metric(rawPattern.rowSpacing, base.pattern.rowSpacing ?? base.pattern.spacing),
      inset: metric(rawPattern.inset, base.pattern.inset),
      offset: typeof rawPattern.offset === 'number' && Number.isFinite(rawPattern.offset)
        ? Math.max(-MAX_METRIC, Math.min(MAX_METRIC, rawPattern.offset))
        : 0,
    },
  }
}

export function sanitizeDrillingMap(input: Partial<Record<string, unknown>> | null | undefined): DrillingMap {
  const source = input ?? {}
  const map = {} as DrillingMap
  for (const role of ALL_PANEL_ROLES) {
    const rules = source[role]
    map[role] = Array.isArray(rules)
      ? rules.slice(0, MAX_RULES_PER_ROLE).map((rule, index) => sanitizeDrillingRule(rule, `${role}-${index}`))
      : []
  }
  return map
}

// ---------------------------------------------------------------------------
// Applying
// ---------------------------------------------------------------------------

/**
 * Expand every enabled rule for a panel's role into operations.
 * Ids are namespaced per rule so two rules on the same role never collide.
 */
export function drillingOperationsForPanel(
  panelKey: string,
  role: PanelRole,
  panel: PanelBox,
  drilling: DrillingMap,
): PanelOperation[] {
  const rules = drilling[role] ?? []
  const out: PanelOperation[] = []

  for (const rule of rules) {
    if (!rule.enabled) continue
    const operations = buildHoleOperations(panelKey, panel, rule.pattern, {
      operationType: rule.operationType,
      diameter: rule.diameter,
      depth: rule.depth,
      through: rule.operationType === 'through-hole',
      face: rule.face,
      headDiameter: rule.headDiameter,
      headDepth: rule.headDepth,
      hardwareCode: rule.hardwareCode ?? undefined,
    })
    for (const op of operations) out.push({ ...op, id: `${rule.id}:${op.id}` })
  }

  return out
}

/** Hardware quantities implied by the drilling across a set of panels. */
export function drillingHardwareCounts(operations: PanelOperation[]): Map<string, number> {
  const counts = new Map<string, number>()
  for (const op of operations) {
    if (!op.hardwareCode) continue
    counts.set(op.hardwareCode, (counts.get(op.hardwareCode) ?? 0) + 1)
  }
  return counts
}
